name: 'coverage'
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  pull_request:
    branches:
      - master
      - main
jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
      - uses: ArtiomTr/jest-coverage-report-action@v2